<script setup>
import { computed, ref } from "vue";
import { get_link, get_chevron } from "../utils";
import ContentViewer from "./ContentViewer.vue";
import Link from "./Link.vue";

const props = defineProps({
	index: { type: Number, required: true },
	content: { type: Object, required: true },
});

const show = ref({
	args: true,
	result: false,
});

function get_status_style(status) {
	if (status === "pending") return "color: var(--gray-600); background-color: var(--gray-100);";
	if (status === "success")
		return "color: var(--green-600); background-color: var(--green-100);";
	if (status === "error") return "color: var(--red-600); background-color: var(--red-100);";
}

const isMetaTool = computed(() => {
	return ["think"].includes(props.content.name);
});
</script>

<template>
	<div class="tool-use">
		<div class="tool-use-header">
			<div class="index-title-container">
				<span :title="`Content Index: ${index + 1}`" class="index">{{ index + 1 }}.</span>

				<!-- Tool Name -->
				<Link
					v-if="content.tool?.name"
					:title="`Tool: ${content.tool?.slug ?? content.name}, Alt Slug: ${
						content.name
					}`"
					:link="get_link('Otto Tool', content.tool?.name)"
					class="tool-name"
				>
					<span class="tool-name-text">{{ content.name }}</span>
					<span
						:title="`${content.name} is a meta tool used to improve task handling`"
						v-if="isMetaTool"
						class="meta-tool-label"
					>
						[meta]</span
					>
				</Link>

				<!-- Tool Name if no link -->
				<p v-else class="tool-name">
					<span class="tool-name-text">{{ content.name }}</span>
					<span
						:title="`${content.name} is a meta tool used to improve task handling`"
						v-if="isMetaTool"
						class="meta-tool-label"
					>
						[meta]</span
					>
				</p>
			</div>

			<p
				:title="`Tool Execution Status: ${content.status}`"
				class="status"
				:style="get_status_style(content.status)"
			>
				{{ content.status }}
			</p>
		</div>

		<!-- Args -->
		<div v-if="content.args" class="tool-use-section">
			<div
				title="Toggle Args. Arguments are generated by the LLM and passed to the tool"
				class="tool-use-section-header"
				@click="show.args = !show.args"
			>
				<p>Args</p>
				<div v-html="get_chevron(show.args)"></div>
			</div>
			<ContentViewer v-if="show.args" :value="content.args" />
		</div>

		<!-- Results -->
		<div v-if="content.result" class="tool-use-section">
			<div
				title="Toggle Result. Result is returned by the tool"
				class="tool-use-section-header"
				@click="show.result = !show.result"
			>
				<p>Result</p>
				<div v-html="get_chevron(show.result)"></div>
			</div>
			<ContentViewer v-if="show.result" :value="content.result" />
		</div>
	</div>
</template>
<style scoped>
.tool-use {
	display: flex;
	flex-direction: column;
	gap: var(--padding-sm);

	.tool-use-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		font-size: var(--text-sm);

		.index-title-container {
			display: flex;
			align-items: center;
			gap: var(--padding-sm);

			.index {
				color: var(--gray-500);
				font-weight: normal;
			}

			.tool-name-text,
			.meta-tool-label {
				font-family: monospace;
			}

			.meta-tool-label {
				font-size: var(--text-xs);
				color: var(--violet-500);
				font-weight: normal;
			}
		}
	}

	.tool-use-section {
		border-top: 1px dashed var(--gray-300);

		p {
			font-size: var(--text-xs);
			color: var(--gray-600);
			margin: 0;
		}

		.tool-use-section-header {
			display: flex;
			justify-content: space-between;
			align-items: center;
			font-size: var(--text-sm);
			padding: var(--padding-xs) 0;
		}

		.tool-use-section-header:hover {
			background-color: var(--gray-50);
			cursor: pointer;
		}
	}

	.tool-use-footer {
		display: flex;
		flex-direction: column;
		gap: var(--padding-sm);
		align-items: start;
	}

	.tool-name {
		font-weight: 600;
		color: var(--gray-700);
		margin: 0;
	}

	.status {
		font-size: var(--text-xs);
		padding: 3px var(--padding-sm);
		text-transform: capitalize;
		margin: 0;
	}
}
</style>
