<script setup>
import { ref } from "vue";
import { get_link } from "../utils";
import ContentViewer from "./ContentViewer.vue";
import Link from "./Link.vue";

const props = defineProps({
	index: { type: Number, required: true },
	content: { type: Object, required: true },
});

const show = ref({
	args: true,
	result: false,
});

function get_status_style(status) {
	if (status === "pending") return "color: var(--gray-600); background-color: var(--gray-100);";
	if (status === "success")
		return "color: var(--green-600); background-color: var(--green-100);";
	if (status === "error") return "color: var(--red-600); background-color: var(--red-100);";
}

function get_chevron(show) {
	let chevron = "chevron-up";
	if (!show) chevron = "chevron-down";
	return frappe.utils.icon(chevron, "sm");
}
</script>

<template>
	<div class="tool-use">
		<div class="tool-use-header">
			<Link
				:title="`Tool: ${content.tool?.slug}, Alt Slug: ${content.name}`"
				:link="get_link('Otto Tool', content.tool?.name)"
				:value="content.name"
				class="tool-name"
			/>
			<p
				:title="`Tool Execution Status: ${content.status}`"
				class="status"
				:style="get_status_style(content.status)"
			>
				{{ content.status }}
			</p>
		</div>

		<!-- Args -->
		<div v-if="content.args" class="tool-use-section">
			<div
				title="Toggle Args. Arguments are generated by the LLM and passed to the tool"
				class="tool-use-section-header"
				@click="show.args = !show.args"
			>
				<p>Args</p>
				<div v-html="get_chevron(show.args)"></div>
			</div>
			<ContentViewer v-if="show.args" :value="content.args" />
		</div>

		<!-- Results -->
		<div v-if="content.result" class="tool-use-section">
			<div
				title="Toggle Result. Result is returned by the tool"
				class="tool-use-section-header"
				@click="show.result = !show.result"
			>
				<p>Result</p>
				<div v-html="get_chevron(show.result)"></div>
			</div>
			<ContentViewer v-if="show.result" :value="content.result" />
		</div>
	</div>
</template>
<style scoped>
.tool-use {
	display: flex;
	flex-direction: column;
	gap: var(--padding-sm);

	.tool-use-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		font-size: var(--text-sm);
	}

	.tool-use-section {
		border-top: 1px dashed var(--gray-300);

		p {
			font-size: var(--text-xs);
			font-family: monospace;
			color: var(--gray-600);
			margin: var(--padding-xs) 0;
		}

		.tool-use-section-header {
			display: flex;
			justify-content: space-between;
			align-items: center;
			font-size: var(--text-sm);
		}

		.tool-use-section-header:hover {
			background-color: var(--gray-50);
			cursor: pointer;
		}
	}

	.tool-use-footer {
		display: flex;
		flex-direction: column;
		gap: var(--padding-sm);
		align-items: start;
	}

	.tool-name {
		font-weight: 600;
		color: var(--gray-700);
	}

	.status {
		font-size: var(--text-xs);
		padding: 3px var(--padding-sm);
		text-transform: capitalize;
		margin: 0;
	}
}
</style>
