<script setup>
import { computed, reactive, ref } from "vue";
import { get_link, get_chevron, safe_stringify, get_status_style } from "../utils";
import ContentViewer from "./ContentViewer.vue";
import Link from "./Link.vue";

const props = defineProps({
	index: { type: Number, required: true },
	content: { type: Object, required: true },
});

const lengths = reactive({
	args: 0,
	result: 0,
});

const show = ref({
	args: showDefault("args"),
	override: showDefault("override"),
	result: showDefault("result") && props.content.name !== "end_task",
});

function showDefault(key) {
	const obj = props.content[key];
	lengths[key] = safe_stringify(obj).length;

	if (typeof obj !== "object" || obj === null) {
		return lengths[key] < 1000;
	}

	const keys = Object.keys(obj).filter((k) => k !== "explanation");
	if (keys.length === 0) return false;

	return lengths[key] < 2000;
}

const isMetaTool = computed(() => {
	return ["think", "end_task"].includes(props.content.name);
});
</script>

<template>
	<div class="tool-use">
		<div class="tool-use-header">
			<div class="index-title-container">
				<span :title="`Content Index: ${index + 1}`" class="index">{{ index + 1 }}.</span>

				<!-- Tool Name -->
				<Link
					v-if="content.tool?.name"
					:title="`Tool: ${content.tool.slug}\nAlt Slug: ${content.name}\nDescription: ${content.tool.description}`"
					:link="get_link('Otto Tool', content.tool.name)"
					class="tool-name"
				>
					<span class="tool-name-text">{{ content.name }}</span>
					<span
						:title="`${content.name} is a meta tool used to assist task handling`"
						v-if="isMetaTool"
						class="meta-tool-label"
					>
						[meta]</span
					>
				</Link>

				<!-- Tool Name if no link -->
				<p v-else class="tool-name" :title="`Tool: ${content.name}`">
					<span class="tool-name-text">{{ content.name }}</span>
					<span
						:title="`${content.name} is a meta tool used to assist task handling`"
						v-if="isMetaTool"
						class="meta-tool-label"
					>
						[meta]</span
					>
				</p>
			</div>

			<p
				:title="`Tool Session Status: ${content.status}`"
				class="status"
				:style="get_status_style(content.status)"
			>
				{{ content.status }}
			</p>
		</div>

		<!-- Args -->
		<div v-if="content.args" class="tool-use-section">
			<div
				title="Toggle Args. Arguments are generated by the LLM and passed to the tool"
				class="tool-use-section-header"
				@click="show.args = !show.args"
			>
				<p>Args</p>
				<div class="chevron-container">
					<p :title="`Length of args when stringified ${lengths.args}`">
						{{ lengths.args }}
					</p>
					<div v-html="get_chevron(show.args)"></div>
				</div>
			</div>
			<ContentViewer v-if="show.args" class="content-viewer" :value="content.args" />
		</div>

		<!-- Args -->
		<div v-if="content.override" class="tool-use-section">
			<div
				title="Toggle Override. Arg overrides are provided by the user"
				class="tool-use-section-header"
				@click="show.override = !show.override"
			>
				<p>Override</p>
				<div class="chevron-container">
					<p :title="`Length of override when stringified ${lengths.override}`">
						{{ lengths.override }}
					</p>
					<div v-html="get_chevron(show.override)"></div>
				</div>
			</div>
			<ContentViewer v-if="show.override" class="content-viewer" :value="content.override" />
		</div>

		<!-- Results -->
		<div v-if="content.result" class="tool-use-section">
			<div
				title="Toggle Result. Result is returned by the tool"
				class="tool-use-section-header"
				@click="show.result = !show.result"
			>
				<p>Result</p>
				<div class="chevron-container">
					<p :title="`Length of result when stringified ${lengths.result}`">
						{{ lengths.result }}
					</p>
					<div v-html="get_chevron(show.result)"></div>
				</div>
			</div>
			<ContentViewer v-if="show.result" class="content-viewer" :value="content.result" />
		</div>
	</div>
</template>
<style scoped>
.tool-use {
	display: flex;
	flex-direction: column;
	gap: var(--padding-sm);

	.tool-use-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		font-size: var(--text-sm);

		.index-title-container {
			display: flex;
			align-items: center;
			gap: var(--padding-sm);

			.index {
				color: var(--gray-500);
				font-weight: normal;
			}

			.tool-name-text,
			.meta-tool-label {
				font-family: monospace;
			}

			.meta-tool-label {
				font-size: var(--text-xs);
				color: var(--violet-500);
				font-weight: normal;
			}
		}
	}

	.tool-use-section {
		border-top: 1px dashed var(--gray-300);

		p {
			font-size: var(--text-xs);
			color: var(--gray-600);
			margin: 0;
		}

		.tool-use-section-header {
			display: flex;
			justify-content: space-between;
			align-items: center;
			font-size: var(--text-sm);
			padding: var(--padding-xs) 0;
		}

		.tool-use-section-header:hover {
			background-color: var(--gray-50);
			cursor: pointer;
		}

		.content-viewer {
			background-color: var(--gray-50);
		}

		.chevron-container {
			display: flex;
			align-items: center;
			gap: var(--padding-md);
			p {
				color: var(--gray-400);
			}
		}
	}

	.tool-use-footer {
		display: flex;
		flex-direction: column;
		gap: var(--padding-sm);
		align-items: start;
	}

	.tool-name {
		font-weight: 600;
		color: var(--gray-700);
		margin: 0;
	}

	.status {
		font-size: var(--text-xs);
		padding: 3px var(--padding-sm);
		text-transform: capitalize;
		margin: 0;
	}
}
</style>
