from typing import NamedTuple

from otto.llm.types import (
	ID,
	Content,
	ContentChunk,
	EndReason,
	FileContent,
	ImageContent,
	Meta,
	ModelSize,
	Provider,
	Query,
	ReasoningEffort,
	Session,
	SessionItem,
	SessionRole,
	SessionStats,
	SessionToolUseStats,
	TextContent,
	ThinkingContent,
	ToolSchema,
	ToolSchemaParameters,
	ToolUseContent,
	ToolUseUpdate,
	UserContent,
)
from otto.otto.doctype.otto_session.otto_session import InteractResponse

__all__ = [
	"ID",
	"Content",
	"ContentChunk",
	"EndReason",
	"FileContent",
	"ImageContent",
	"InteractResponse",
	"Meta",
	"ModelSize",
	"Provider",
	"Query",
	"ReasoningEffort",
	"Session",
	"SessionItem",
	"SessionRole",
	"SessionStats",
	"SessionToolUseStats",
	"TextContent",
	"ThinkingContent",
	"ToolSchema",
	"ToolSchemaParameters",
	"ToolUseContent",
	"ToolUseUpdate",
	"UserContent",
]


class PendingToolUse(NamedTuple):
	"""
	Represents a pending tool use request from the LLM.

	Attributes:
		id: The unique tool use ID assigned by the API
		name: The slug/identifier name of the tool to be invoked
		args: Dictionary of argument values generated by the LLM to be passed to the tool
	"""

	id: str
	name: str
	args: dict
